import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceKey);

    const { auth_user_id, full_name, email, phone, role, student_id_number, id_passport_number } = await req.json();

    if (!auth_user_id || !full_name || !email || !role) {
      return new Response(JSON.stringify({ error: "Missing required fields" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Map signup role to school_user_role
    const roleMap: Record<string, string> = {
      student: "student",
      parent: "parent",
      educator: "educator",
    };
    const schoolRole = roleMap[role] || "student";

    // Create the school_user entry (no school_id - user will link later)
    // user_code is auto-generated by the trigger
    const { data: insertedUser, error: insertError } = await supabase
      .from("school_users")
      .insert({
        user_id: auth_user_id,
        school_id: null,
        role: schoolRole,
        full_name,
        email,
        phone: phone || null,
        student_id_number: student_id_number || null,
        id_passport_number: id_passport_number || null,
        is_active: true,
      })
      .select("id, user_code")
      .single();

    if (insertError) {
      console.error("Insert error:", insertError);
      return new Response(JSON.stringify({ error: insertError.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const userCode = insertedUser.user_code;
    const results: { sms?: string; email?: string } = {};

    // Send SMS with user_code if phone exists
    if (phone) {
      try {
        const twilioSid = Deno.env.get("TWILIO_ACCOUNT_SID");
        const twilioAuth = Deno.env.get("TWILIO_AUTH_TOKEN");
        const messagingSid = Deno.env.get("TWILIO_MESSAGING_SERVICE_SID");

        if (twilioSid && twilioAuth && messagingSid) {
          const cleanPhone = phone.replace(/\s/g, "");
          const body = `Welcome to edLEAD, ${full_name}! Your edLEAD ID is: ${userCode}. You can use this ID, your email, or phone number to log in at edlead.co.za/portal/login`;

          const twilioUrl = `https://api.twilio.com/2010-04-01/Accounts/${twilioSid}/Messages.json`;
          const twilioResp = await fetch(twilioUrl, {
            method: "POST",
            headers: {
              "Authorization": "Basic " + btoa(`${twilioSid}:${twilioAuth}`),
              "Content-Type": "application/x-www-form-urlencoded",
            },
            body: new URLSearchParams({
              MessagingServiceSid: messagingSid,
              To: cleanPhone,
              Body: body,
            }),
          });

          results.sms = twilioResp.ok ? "sent" : "failed";
        }
      } catch {
        results.sms = "failed";
      }
    }

    // Send email with user_code
    try {
      const resendKey = Deno.env.get("RESEND_API_KEY");
      if (resendKey) {
        const emailResp = await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: {
            "Authorization": `Bearer ${resendKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            from: "edLEAD <noreply@edlead.co.za>",
            to: [email],
            subject: "Welcome to edLEAD — Your edLEAD ID",
            html: `
              <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px;">
                <div style="text-align:center;margin-bottom:20px;">
                  <img src="https://edlead.co.za/images/edlead-logo-email-header.png" alt="edLEAD" style="height:50px;" />
                </div>
                <h2 style="color:#ED7621;">Welcome to edLEAD!</h2>
                <p>Dear ${full_name},</p>
                <p>Your account has been created successfully. Here are your login details:</p>
                <div style="background:#f5f5f5;border-radius:8px;padding:20px;margin:20px 0;text-align:center;">
                  <p style="margin:0 0 8px 0;color:#666;font-size:14px;">Your edLEAD ID</p>
                  <p style="margin:0;font-size:28px;font-weight:bold;color:#ED7621;letter-spacing:2px;">${userCode}</p>
                </div>
                <p>You can log in using any of the following:</p>
                <ul>
                  <li><strong>Email:</strong> ${email}</li>
                  ${phone ? `<li><strong>Phone:</strong> ${phone}</li>` : ""}
                  <li><strong>edLEAD ID:</strong> ${userCode}</li>
                </ul>
                <p>Once logged in, you can link your account to a school from your portal dashboard.</p>
                <p>Visit <a href="https://edlead.lovable.app/portal/login" style="color:#ED7621;">edlead.lovable.app/portal/login</a> to sign in.</p>
                <hr style="margin:20px 0;border:none;border-top:1px solid #eee;" />
                <p style="color:#999;font-size:12px;">This is an automated message from edLEAD. Please do not reply.</p>
              </div>
            `,
          }),
        });

        results.email = emailResp.ok ? "sent" : "failed";
      }
    } catch {
      results.email = "failed";
    }

    return new Response(
      JSON.stringify({ success: true, user_code: userCode, notifications: results }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    console.error("Server error:", err);
    return new Response(
      JSON.stringify({ error: "Server error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
