import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Loader2, UserCheck, Search } from "lucide-react";
import { format } from "date-fns";

export function AdminEventAttendanceTab() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [filterEventId, setFilterEventId] = useState<string>("all");
  const [searchTerm, setSearchTerm] = useState("");
  const [checkInOpen, setCheckInOpen] = useState(false);
  const [checkInForm, setCheckInForm] = useState({
    event_id: "",
    attendee_name: "",
    phone: "",
    booking_ref: "",
  });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const { data: events } = useQuery({
    queryKey: ["admin-events-list"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("events")
        .select("id, title")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data;
    },
  });

  const { data: attendance, isLoading } = useQuery({
    queryKey: ["admin-event-attendance", filterEventId, searchTerm],
    queryFn: async () => {
      let query = supabase
        .from("event_attendance")
        .select("*, events(title)")
        .order("checked_in_at", { ascending: false });

      if (filterEventId && filterEventId !== "all") {
        query = query.eq("event_id", filterEventId);
      }
      if (searchTerm.trim()) {
        query = query.or(`attendee_name.ilike.%${searchTerm}%,ticket_number.ilike.%${searchTerm}%`);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data;
    },
  });

  const handleCheckIn = async () => {
    if (!checkInForm.event_id || !checkInForm.attendee_name) {
      toast({ title: "Event and attendee name are required", variant: "destructive" });
      return;
    }

    setIsSubmitting(true);
    try {
      // Look up booking by reference if provided
      let bookingId: string | null = null;
      if (checkInForm.booking_ref.trim()) {
        const { data: booking } = await supabase
          .from("event_bookings")
          .select("id")
          .eq("reference_number", checkInForm.booking_ref.trim())
          .eq("event_id", checkInForm.event_id)
          .maybeSingle();
        bookingId = booking?.id || null;
      }

      // Insert attendance record (ticket_number auto-generated by trigger)
      const { data: record, error } = await supabase
        .from("event_attendance")
        .insert({
          event_id: checkInForm.event_id,
          booking_id: bookingId,
          attendee_name: checkInForm.attendee_name.trim(),
          phone: checkInForm.phone.trim() || null,
          ticket_number: "", // trigger will generate
        })
        .select("*, events(title)")
        .single();

      if (error) throw error;

      // Send notification via edge function
      if (record.phone) {
        const eventTitle = (record as any).events?.title || "Event";
        try {
          await supabase.functions.invoke("notify-event-checkin", {
            body: {
              attendeeName: record.attendee_name,
              ticketNumber: record.ticket_number,
              eventTitle,
              phone: record.phone,
            },
          });

          // Mark notification sent
          await supabase
            .from("event_attendance")
            .update({ notification_sent: true })
            .eq("id", record.id);
        } catch (notifErr) {
          console.error("Notification error:", notifErr);
        }
      }

      queryClient.invalidateQueries({ queryKey: ["admin-event-attendance"] });
      toast({
        title: "Checked In",
        description: `${record.attendee_name} — Ticket: ${record.ticket_number}`,
      });
      setCheckInOpen(false);
      setCheckInForm({ event_id: "", attendee_name: "", phone: "", booking_ref: "" });
    } catch (err: any) {
      console.error(err);
      toast({ title: "Check-in failed", description: err.message, variant: "destructive" });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-end gap-4">
        <h3 className="text-lg font-semibold mr-auto">Event Attendance</h3>
        <div className="flex items-end gap-3">
          <div>
            <Label className="text-xs text-muted-foreground">Filter by Event</Label>
            <Select value={filterEventId} onValueChange={setFilterEventId}>
              <SelectTrigger className="w-[200px] h-9">
                <SelectValue placeholder="All Events" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Events</SelectItem>
                {events?.map((e) => (
                  <SelectItem key={e.id} value={e.id}>{e.title}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="relative">
            <Label className="text-xs text-muted-foreground">Search</Label>
            <div className="relative">
              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                className="pl-8 w-[200px] h-9"
                placeholder="Name or ticket..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
          </div>
          <Button onClick={() => setCheckInOpen(true)}>
            <UserCheck className="h-4 w-4 mr-2" />
            Check In
          </Button>
        </div>
      </div>

      {/* Check-in dialog */}
      <Dialog open={checkInOpen} onOpenChange={setCheckInOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Check In Attendee</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label>Event *</Label>
              <Select value={checkInForm.event_id} onValueChange={(v) => setCheckInForm({ ...checkInForm, event_id: v })}>
                <SelectTrigger><SelectValue placeholder="Select event" /></SelectTrigger>
                <SelectContent>
                  {events?.map((e) => (
                    <SelectItem key={e.id} value={e.id}>{e.title}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Booking Reference <span className="text-muted-foreground text-xs">(optional)</span></Label>
              <Input
                value={checkInForm.booking_ref}
                onChange={(e) => setCheckInForm({ ...checkInForm, booking_ref: e.target.value })}
                placeholder="e.g. EVB-123456"
              />
            </div>
            <div>
              <Label>Attendee Name *</Label>
              <Input
                value={checkInForm.attendee_name}
                onChange={(e) => setCheckInForm({ ...checkInForm, attendee_name: e.target.value })}
                placeholder="Full name"
              />
            </div>
            <div>
              <Label>Phone <span className="text-muted-foreground text-xs">(for SMS/WhatsApp notification)</span></Label>
              <Input
                value={checkInForm.phone}
                onChange={(e) => setCheckInForm({ ...checkInForm, phone: e.target.value })}
                placeholder="+27..."
              />
            </div>
            <Button className="w-full" onClick={handleCheckIn} disabled={isSubmitting}>
              {isSubmitting && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              Check In & Send Notification
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {isLoading ? (
        <div className="flex justify-center py-8"><Loader2 className="h-6 w-6 animate-spin" /></div>
      ) : (
        <div className="rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Ticket #</TableHead>
                <TableHead>Event</TableHead>
                <TableHead>Attendee</TableHead>
                <TableHead>Phone</TableHead>
                <TableHead>Checked In</TableHead>
                <TableHead>Notified</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {attendance?.map((a: any) => (
                <TableRow key={a.id}>
                  <TableCell className="font-mono text-xs font-semibold">{a.ticket_number}</TableCell>
                  <TableCell>{a.events?.title || "—"}</TableCell>
                  <TableCell className="font-medium">{a.attendee_name}</TableCell>
                  <TableCell className="text-sm">{a.phone || "—"}</TableCell>
                  <TableCell className="text-sm">{format(new Date(a.checked_in_at), "dd MMM yyyy, HH:mm")}</TableCell>
                  <TableCell>
                    <Badge variant={a.notification_sent ? "default" : "secondary"}>
                      {a.notification_sent ? "Sent" : "No"}
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
              {attendance?.length === 0 && (
                <TableRow>
                  <TableCell colSpan={6} className="text-center text-muted-foreground py-8">
                    No attendance records yet. Use "Check In" to register attendees.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </div>
      )}
    </div>
  );
}
